[package]
name = "factorial_calculation"
version = "0.1.0"
edition = "2021"
authors = "Ali Hameed <ahahswe@gmail.com>"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
